// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/kaigoh/monate/v2/graph/scalar"
)

type CreateInvoiceInput struct {
	StoreID      string      `json:"storeId"`
	AmountAtomic scalar.Long `json:"amountAtomic"`
	FiatAmount   float64     `json:"fiatAmount"`
	Currency     string      `json:"currency"`
	Description  *string     `json:"description,omitempty"`
	Reference    *string     `json:"reference,omitempty"`
}

type CreateStoreInput struct {
	Name              string              `json:"name"`
	Slug              string              `json:"slug"`
	PublicURL         string              `json:"publicUrl"`
	MoneroPayEndpoint string              `json:"moneroPayEndpoint"`
	MoneroPayAPIKey   string              `json:"moneroPayApiKey"`
	Theme             *ThemeSettingsInput `json:"theme,omitempty"`
}

type Invoice struct {
	ID               string        `json:"id"`
	StoreID          string        `json:"storeId"`
	Store            *Store        `json:"store"`
	Description      *string       `json:"description,omitempty"`
	Reference        *string       `json:"reference,omitempty"`
	AmountAtomic     scalar.Long   `json:"amountAtomic"`
	ExpectedAmount   scalar.Long   `json:"expectedAmount"`
	Currency         string        `json:"currency"`
	FiatAmount       float64       `json:"fiatAmount"`
	MoneroPayAddress string        `json:"moneroPayAddress"`
	Status           InvoiceStatus `json:"status"`
	Complete         bool          `json:"complete"`
	CoveredTotal     scalar.Long   `json:"coveredTotal"`
	CoveredUnlocked  scalar.Long   `json:"coveredUnlocked"`
	ManualCheckCount int32         `json:"manualCheckCount"`
	CreatedAt        time.Time     `json:"createdAt"`
	UpdatedAt        time.Time     `json:"updatedAt"`
	ResolvedAt       *time.Time    `json:"resolvedAt,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Store struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Slug      string         `json:"slug"`
	PublicURL string         `json:"publicUrl"`
	Theme     *ThemeSettings `json:"theme"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
}

type Subscription struct {
}

type ThemeSettings struct {
	PrimaryColor   string  `json:"primaryColor"`
	AccentColor    string  `json:"accentColor"`
	BackgroundURL  *string `json:"backgroundUrl,omitempty"`
	LogoURL        *string `json:"logoUrl,omitempty"`
	Headline       *string `json:"headline,omitempty"`
	CustomCopy     *string `json:"customCopy,omitempty"`
	ShowFiatAmount bool    `json:"showFiatAmount"`
	ShowTicker     bool    `json:"showTicker"`
	PresetAmounts  []int32 `json:"presetAmounts"`
}

type ThemeSettingsInput struct {
	PrimaryColor   *string `json:"primaryColor,omitempty"`
	AccentColor    *string `json:"accentColor,omitempty"`
	BackgroundURL  *string `json:"backgroundUrl,omitempty"`
	LogoURL        *string `json:"logoUrl,omitempty"`
	Headline       *string `json:"headline,omitempty"`
	CustomCopy     *string `json:"customCopy,omitempty"`
	ShowFiatAmount *bool   `json:"showFiatAmount,omitempty"`
	ShowTicker     *bool   `json:"showTicker,omitempty"`
	PresetAmounts  []int32 `json:"presetAmounts,omitempty"`
}

type UpdateStoreThemeInput struct {
	StoreID string              `json:"storeId"`
	Theme   *ThemeSettingsInput `json:"theme"`
}

type InvoiceStatus string

const (
	InvoiceStatusPending  InvoiceStatus = "PENDING"
	InvoiceStatusPaid     InvoiceStatus = "PAID"
	InvoiceStatusExpired  InvoiceStatus = "EXPIRED"
	InvoiceStatusCanceled InvoiceStatus = "CANCELED"
)

var AllInvoiceStatus = []InvoiceStatus{
	InvoiceStatusPending,
	InvoiceStatusPaid,
	InvoiceStatusExpired,
	InvoiceStatusCanceled,
}

func (e InvoiceStatus) IsValid() bool {
	switch e {
	case InvoiceStatusPending, InvoiceStatusPaid, InvoiceStatusExpired, InvoiceStatusCanceled:
		return true
	}
	return false
}

func (e InvoiceStatus) String() string {
	return string(e)
}

func (e *InvoiceStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InvoiceStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InvoiceStatus", str)
	}
	return nil
}

func (e InvoiceStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InvoiceStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InvoiceStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
